# Data configs
domainA_dir: 'D:\FaceAging-master\face_gan\UTK_Face\15-20'
domainB_dir: 'D:\FaceAging-master\face_gan\UTK_Face\20-25'
domain_dirs: [
    'D:\FaceAging-master\face_gan\UTK_Face\15-20', 
    'D:\FaceAging-master\face_gan\UTK_Face\20-25',
    'D:\FaceAging-master\face_gan\UTK_Face\25-30',
    'D:\FaceAging-master\face_gan\UTK_Face\30-35',
    'D:\FaceAging-master\face_gan\UTK_Face\35-40',
    'D:\FaceAging-master\face_gan\UTK_Face\40-45',
    'D:\FaceAging-master\face_gan\UTK_Face\45-50',
    ]
# Network Configs
ngf: 32
ndf: 32
n_blocks: 9

# Loss configs:
adv_weight: 2
cycle_weight: 10
identity_weight: 7

# Optimizer configs:
lr: 0.0001
weight_decay: 0.0001

# Training configs:
img_size: 256
batch_size: 16
num_workers: 4
epochs: 100
augment_rotation: 80
gpus: 
  -1
